import Head from 'next/head'
import {Navbar} from '../Navbar'
import {FC} from 'react'

import styles from './MainLayout.module.css'

interface Props {
    children: React.ReactNode;
  }

export const MainLayout:FC<Props> = ({children}) => {
    return (
        <div className={styles.container}>
            <Head>
                <title>Home Page Jimmito</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
        
            <Navbar/>
        
            <main className={styles.main}>

                {children}
                
            </main>
    
        </div>
      )
}
